### ISSUE TITLE
Error rego_type_error: undefined function redis.get on running opa as server.

### ISSUE THREAD

**Issue by anuraagramesh** [tibotix/opa-redis-plugin#10]
I am getting the below error after registering this plugin and running `opa run` as a server. 

Steps to reproduce : 

1. Run Redis instance locally at `localhost:6379`
2. Create a new folder and navigate into it. 
3. Command - `go mod init opa-redis-plugin`
4. Create file - main.go (attached)
5. Command - `go mod tidy`
6. Command - `go build -o opa++`
7. Create file - config.yaml (attached)
8. Create file - main.rego (attached)
9. Command - `./opa++ run -s -c config.yaml ./main.rego`

The last command above (8) results in the below error : 

`error: initialization error: 1 error occurred: ./main.rego:6: rego_type_error: undefined function redis.get`

Expected output : 

The server should start successfully and we should be able to make http calls to it. 

main.go 

```
package main

import (
	"os"

	"github.com/open-policy-agent/opa/cmd"
	"github.com/open-policy-agent/opa/runtime"

	opa_redis_plugin "github.com/tibotix/opa-redis-plugin/plugin"
)

func main() {
	runtime.RegisterPlugin(opa_redis_plugin.PluginName, opa_redis_plugin.Factory{})

	if err := cmd.RootCommand.Execute(); err != nil {
		os.Exit(1)
	}
}
```

config.yaml

```
plugins:
  redis:
    enabled: true
    address: "redis://default@127.0.0.1:6379/0"
    max_retries: 3
    dial_timeout_in_seconds: 8.0
    read_timeout_in_seconds: 2.0

```

main.rego

```
package main

default allow := false                              # unless otherwise defined, allow is false

allow := true {                                     # allow is true if...
    redis.get("xyz") == "1"                          # there are zero violations.
}
```

Additional note : 

Running opa as interactive shell without the rego policy (main.rego) and then executing redis commands works fine and is able to get/set values from locally running Redis instance. 

`./opa++ run -c config.yaml`

**Comment by anuraagramesh** [comment]
I have created [this](https://github.com/open-policy-agent/opa/issues/6427) issues on the OPA repository in case it is an issue with their plugin configuration.

**Comment by tibotix** [comment]
Hey, thanks for your issue.
I think the problem is the missing handling of plug-in states, that are propagated to the OPA runtime via `Plugin.UpdatePluginStatus`. I will try to implement this and see if it works then.

**Comment by tibotix** [comment]
Unfortunately that didn't work. Probably this is an issue where opa parses the policy file first and then instantiates plugins. Maybe OPA has a solution for that, but i am not aware of it. As a work around,  you could specify the policy after the plugin instantiations through a policy bundle.

**Comment by anuraagramesh** [comment]
Hey @tibotix , thanks for your response. I tried passing the policy through a bundle but that fails with the same error as well. Sharing the steps here in case you are thinking of a different approach. 

1. `opa build -b .` - fails with same error
2. As a workaround, I did - `tar -czf bundle.tar.gz main.rego` and then `./opa++ run --bundle ./bundle/bundle.tar.gz` - fails with same error

**Comment by anuraagramesh** [comment]
I was able to get some inputs from OPA team about this issue. Could you please look at the below comments to see if it helps? 

https://github.com/open-policy-agent/opa/issues/6427#issuecomment-1825202919
https://github.com/open-policy-agent/opa/issues/6427#issuecomment-1825278099

**Comment by tibotix** [comment]
I made changes according the comments. Let me know if it works now for you :)

**Comment by anuraagramesh** [comment]
Thanks so much @tibotix for your prompt response. I tested with the updated code and it is working as expected. I am closing the issue now.

**Comment by tibotix** [comment]
Great, glad to hear :) 
The naming / design choices I made are not the best, so maybe in the future if I have more time I will refactor it. Unfortunately this project is not my current priority. Nevertheless, great that it works now!
